name: PDF to HTML Converter

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  convert-pdfs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          
      - name: Monitor for new PDFs
        run: python scripts/monitor.py
        
      - name: Download new PDFs
        run: python scripts/download.py
        
      - name: Start GROBID service
        run: |
          docker run --rm -d --name grobid -p 8070:8070 lfoppiano/grobid:0.7.2
          # Wait for GROBID to start
          echo "Waiting for GROBID to start..."
          for i in {1..10}; do
            if curl -s http://localhost:8070/api/isalive > /dev/null; then
              echo "GROBID is ready!"
              break
            fi
            echo "Waiting for GROBID to start (attempt $i/10)..."
            sleep 5
          done
          
      - name: Convert PDFs to HTML using GROBID
        run: python scripts/convert.py
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/html
          force_orphan: true
